DEFAULT_MODULES = [
    "seo_generation",
    "rank_tracking",
    "competitor_insights",
    "auto_apply",
    "sales_stats",
    "user_profile",
    "wb_reviews_ai",
    "wb_questions_ai",
    "returns",
    "wb_ads",
    "wb_ads_analytics",
    "wb_ads_recommendations",
    "help_center",
    "ai_assistant",
    "billing",
]
